python3 train.py --dataset SimpleFashionClassification \
                 --save_path results \
                 --epoch 25 \
                 --size 128 \
                 --batch_size 32 \
                 --aug_mode special \
                 --arch resnet50 \
                 --lr 0.001 \
                 --lr_milestones 5 10 15 20 \
                 --scheduler_gamma 0.5 \
                 --version 0.1
